export enum SOCKET_EVENTS {
  SEND_FILE = "SEND_FILE",
  WAIT_TRANSFER_ACCEPTED = "WAIT_TRANSFER_ACCEPTED",
  SUCCESS_TRANSFER = "SUCCESS_TRANSFER",
  ERROR_TRANSFER = "ERROR_TRANSFER",
  NEW_CONNECTION = "NEW_CONNECTION",
}
